import Thumbnail from "./assets/Thumbnail.png";
const dummyGridData = [
  {
    id: 1,
    title: "Learn English Basics",
    length: "10:23",
    creator: "Jamie Furlong",
    level: "A1",
    topic: "Grammar",
    accent: "British",
    thumbnail: Thumbnail,
    url: "https://www.youtube.com/watch?v=F3wsy8bywXQ",
    description:
      "A beginner-friendly introduction to English grammar, using the catchy rhythms of a Eurovision classic to make learning fun and memorable.",
  },
  {
    id: 2,
    title: "Advanced Vocabulary Tips",
    length: "15:45",
    creator: "Rebecca Rogers",
    level: "C1",
    topic: "Vocabulary",
    accent: "American",
    thumbnail: Thumbnail,
    url: "https://www.youtube.com/watch?v=2AN3vvLORuw",
    description:
      "Expand your English vocabulary with advanced tips, set to the energetic beats of a Eurovision performance.",
  },
  {
    id: 3,
    title: "Common English Mistakes",
    length: "12:30",
    creator: "James Mcintosh",
    level: "B2",
    topic: "Grammar",
    accent: "Irish",
    thumbnail: Thumbnail,
    url: "https://www.youtube.com/watch?v=wlZSQZm8j8c",
    description:
      "Learn how to avoid common English mistakes while enjoying a Eurovision song that makes grammar engaging.",
  },
  {
    id: 4,
    title: "English Idioms Explained",
    length: "8:50",
    creator: "Ayush Goyal",
    level: "B1",
    topic: "Idioms",
    accent: "Australian",
    thumbnail: Thumbnail,
    url: "https://www.youtube.com/watch?v=RZ0hqX_92zI",
    description:
      "Discover the meaning behind popular English idioms, explained with the help of a memorable Eurovision entry.",
  },
  {
    id: 5,
    title: "Mastering Pronunciation",
    length: "20:10",
    creator: "Phuc Long",
    level: "B2",
    topic: "Pronunciation",
    accent: "Canadian",
    thumbnail: Thumbnail,
    url: "https://www.youtube.com/watch?v=BE2Fj0W4jP4",
    description:
      "Improve your English pronunciation by practicing along with a Eurovision song, focusing on clear and accurate sounds.",
  },
  {
    id: 6,
    title: "English for Business",
    length: "18:05",
    creator: "Rebecca Rogers",
    level: "C1",
    topic: "Business",
    accent: "American",
    thumbnail: Thumbnail,
    url: "https://www.youtube.com/watch?v=Pfo-8z86x80",
    description:
      "Learn essential business English phrases and etiquette, inspired by the professionalism and flair of a Eurovision performance.",
  },
  {
    id: 7,
    title: "Quick English Phrases",
    length: "5:30",
    creator: "Jamie Furlong",
    level: "A2",
    topic: "Phrases",
    accent: "British",
    thumbnail: Thumbnail,
    url: "https://www.youtube.com/watch?v=5sGOwFVUU0I",
    description:
      "Pick up useful English phrases for everyday situations, taught through the lyrics and energy of a Eurovision hit.",
  },
  {
    id: 8,
    title: "English Listening Practice",
    length: "25:00",
    creator: "James Mcintosh",
    level: "B2",
    topic: "Listening",
    accent: "Irish",
    thumbnail: Thumbnail,
    url: "https://www.youtube.com/watch?v=WXwgZL4zx9o",
    description:
      "Sharpen your listening skills with real Eurovision lyrics and commentary, perfect for intermediate learners.",
  },
  {
    id: 9,
    title: "How to Write Emails",
    length: "14:20",
    creator: "Ayush Goyal",
    level: "B1",
    topic: "Writing",
    accent: "Australian",
    thumbnail: Thumbnail,
    url: "https://www.youtube.com/watch?v=pHXDMe6QV-U",
    description:
      "Master the art of writing professional emails in English, with tips and examples inspired by Eurovision song themes.",
  },
  {
    id: 10,
    title: "English for Travel",
    length: "9:45",
    creator: "Phuc Long",
    level: "A2",
    topic: "Travel",
    accent: "Canadian",
    thumbnail: Thumbnail,
    url: "https://www.youtube.com/watch?v=R3D-r4ogr7s",
    description:
      "Learn essential English for travel, using Eurovision songs to make key phrases and vocabulary easy to remember.",
  },
];

export default dummyGridData;
